/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author 5586658
 */
public class Teste extends javax.swing.JFrame {

    private Executor executor = Executors.newCachedThreadPool();
    /**
     * Creates new form Teste
     */
    public Teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTopo = new javax.swing.JPanel();
        campoTextoURL = new javax.swing.JTextField();
        botaoDownload = new javax.swing.JButton();
        painelConteudo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelTopo.setLayout(new java.awt.BorderLayout());

        campoTextoURL.setText("https://download-installer.cdn.mozilla.net/pub/firefox/releases/46.0.1/win32/pt-BR/Firefox%20Setup%2046.0.1.exe");
        campoTextoURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoURLActionPerformed(evt);
            }
        });
        painelTopo.add(campoTextoURL, java.awt.BorderLayout.CENTER);

        botaoDownload.setText("Download");
        botaoDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDownloadActionPerformed(evt);
            }
        });
        painelTopo.add(botaoDownload, java.awt.BorderLayout.EAST);

        getContentPane().add(painelTopo, java.awt.BorderLayout.NORTH);

        painelConteudo.setLayout(new javax.swing.BoxLayout(painelConteudo, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(painelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDownloadActionPerformed
        String url = campoTextoURL.getText();
        DownloadTask task = new DownloadTask(url);
        
        task.addListener(new DownloaderListener() {
            private JProgressBar barraProgresso = new JProgressBar();
            
            @Override
            public void downloadStarted(String link, long totalSize) {
                barraProgresso.setValue(barraProgresso.getMinimum());
                
                painelConteudo.add(barraProgresso);
                
                painelConteudo.revalidate();
            }

            @Override
            public void downloadFinished() {
                barraProgresso.setValue(barraProgresso.getMaximum());
            }

            @Override
            public void downloadProgress(long totalSize, long downloadedBytes) {
                SwingUtilities.invokeLater(() ->{
                    double p = (double)downloadedBytes/totalSize * 100;
                    barraProgresso.setValue((int)p);
                });
            }
        });
        
        executor.execute(task);
    }//GEN-LAST:event_botaoDownloadActionPerformed

    private void campoTextoURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoURLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDownload;
    private javax.swing.JTextField campoTextoURL;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelTopo;
    // End of variables declaration//GEN-END:variables
}
